### ISSUE TITLE
Uncaught ReferenceError: <component> is not defined

### ISSUE THREAD

**Issue by danguyenwork** [suzan2go/react-rails-redux-sample#13]
Hi @suzan2go 

First of all, thanks for the awesome sample!

I have a quick question. Unless I manually declare components inside `components.js`, I get a `UncaughtReferrenceError`

```
global.FilterableProductTable = require( 'components/filterable_product_table.es6.jsx' ).default;
```

Do you have any idea why? I have tried adding `//= require components` to `application.js` and `require( './components' );` to `components.js` with no success

Thank you.

**Comment by suusan2go** [comment]
Hi @adnguyen1989 .

> I have a quick question. Unless I manually declare components inside components.js, I get a UncaughtReferrenceError

This is because if you use react-rails, the react component needs to be globally accessible.

https://github.com/reactjs/react-rails#rendering--mounting
> component_class_name is a string which names a globally-accessible component class. It may have dots (eg, "MyApp.Header.MenuItem").
