### ISSUE TITLE
Error while trying get welcome#index

### ISSUE THREAD

**Issue by kalashnikovisme** [suzan2go/react-rails-redux-sample#5]
Error while running `/home/pavel/projects/react-rails-redux-sample/node_modules/.bin/browserifyinc -t babelify --list --cachefile=/home/pavel/projects/react-rails-redux-sample/tmp/cache/browserify-rails/browserifyinc-cache.json -o "/home/pavel/projects/react-rails-redux-sample/tmp/cache/browserify-rails/output20160329-23163-17hjpm7" -`:

/usr/bin/env: node: No such file or directory

  (in /home/pavel/projects/react-rails-redux-sample/app/assets/javascripts/components.js)

**Comment by suusan2go** [comment]
closed at #6
