### ISSUE TITLE
Enhancement: tests

### ISSUE THREAD

**Issue by BjornMelgaard** [suzan2go/react-rails-redux-sample#8]
Want to say thanks for example, though it would be great if it show the ways one could write tests for js.
Currently I search these ways.
Do you have some ideas?

**Comment by suzan2go** [comment]
@BjornMelgaard 
Hi, I‘ve added two test examples. One is E2E test by capybara, the other is js unit tests by   [enzyme](https://github.com/airbnb/enzyme).

Please check  #10 .

**Comment by BjornMelgaard** [comment]
Thanks for attention.
Also, if someone read this and be interested, I done big application on react+immutable by this example, it has much of tests on jasmine
https://github.com/BjornMelgaard/react-todolist/tree/development/spec/javascripts
